using Microsoft.EntityFrameworkCore;
using ScrumPilot.Data.Context;
using ScrumPilot.Shared.Models;

namespace ScrumPilot.Data.Repositories
{
    public class PbiRepository : IPbiRepository
    {
        private readonly ScrumPilotContext _context;

        public PbiRepository(ScrumPilotContext context)
        {
            _context = context;
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetAllPbisAsync()
        {
            return await _context.Stories
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        //public async Task<IEnumerable<Story>> GetActiveStoriesAsync(epicId)
        //{
        //    return await _context.Stories
        //        .Where(s => s.EpicId == epicId && s.Status != StoryStatus.Closed)
        //        .OrderByDescending(s => s.DateCreated)
        //        .ToListAsync();
        //}

        public async Task<ProductBacklogItem?> GetByIdAsync(int id)
        {
            return await _context.Stories
                .FirstOrDefaultAsync(s => s.PbiId == id);
        }

        public async Task<ProductBacklogItem> AddAsync(ProductBacklogItem story)
        {
            // Note: Id will be auto-generated by the database (identity column)
            _context.Stories.Add(story);
            await _context.SaveChangesAsync();
            return story;
        }

        public async Task<ProductBacklogItem> UpdateAsync(ProductBacklogItem story)
        {
            _context.Entry(story).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return story;
        }

        public async Task<bool> DeleteAsync(int id) //This is a full delete right now. We may want to consider a soft delete. To Be Determined - TB
        {
            var story = await _context.Stories.FindAsync(id);
            if (story == null)
            {
                return false;
            }

            _context.Stories.Remove(story);
            await _context.SaveChangesAsync();
            return true;
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetByStatusAsync(PbiStatus status)
        {
            return await _context.Stories
                .Where(s => s.Status == status)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetDraftPbisAsync()
        {
            return await _context.Stories
                .Where(s => s.IsDraft)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetNonDraftPbisAsync()
        {
            return await _context.Stories
                .Where(s => !s.IsDraft)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetFilteredPbisAsync(int? sprintId, int? epicId)
        {
            var query = _context.Stories.Where(s => !s.IsDraft);

            if (sprintId.HasValue)
            {
                if (sprintId.Value == -1)
                    query = query.Where(s => s.SprintId == null);
                else
                    query = query.Where(s => s.SprintId == sprintId.Value);
            }

            if (epicId.HasValue)
                query = query.Where(s => s.EpicId == epicId.Value);

            return await query
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }
    }
}